### ISSUE TITLE
数学公式前面有多余的间距

### ISSUE THREAD

**Issue by EndlessXYZ** [Achuan-2/siyuan-themes-tsundoku-dark#1]
数学公式前面有多余的间距：
![图片](https://user-images.githubusercontent.com/57283205/109807866-67cb9800-7c61-11eb-9d74-fe25ceb599a7.png)

## 修复方法：

把CSS的
```/* 行内代码块 */
.vditor-reset code:not(.hljs){
        ...
}
```
改为
```/* 行内代码块 */
.vditor-reset code:not(.hljs):not([data-type="math-inline"]) {
        ...
}
```

（很喜欢这个主题，加油！）

**Comment by Achuan-2** [comment]
ok，谢谢支持，稍晚点更新主题。
有其他问题也欢迎提哦，现在基本是个人使用过程中发现出问题再优化
