### ISSUE TITLE
字体颜色由设置的黄色变为了白色，上个版本还是正常的

### ISSUE THREAD

**Issue by alphaleek** [Achuan-2/siyuan-themes-tsundoku-dark#10]
https://user-images.githubusercontent.com/76611744/129660574-19ab8977-92d2-466b-bf3c-392d4c3684ff.mp4

**Comment by Achuan-2** [comment]
是因为调整了自定义颜色，并且与官方的颜色不一致
目前更改字体颜色是css变量实现的，如果主题修改了css变量，切换主题就会改变颜色。这点如果切换notion主题可能会更严重

官方的
![image](https://user-images.githubusercontent.com/60436214/129687375-580c2b07-6a15-478a-8283-93aeb6138cab.png)
我修改的
![image](https://user-images.githubusercontent.com/60436214/129687419-391c73fe-844f-4005-ad35-de0dc102c039.png)

由于主题设计的颜色与官方有出入，多少都会有颜色的改变的

**Comment by Achuan-2** [comment]
有需要的可以自行修改，或是直接粘贴官方主题的颜色配色

**Comment by Achuan-2** [comment]
我试着调整一下顺序，尽量让主题颜色和官方颜色色差不太大

**Comment by alphaleek** [comment]
> 我开始调整一下顺序，尽量让主题颜色和官方颜色不太大

感谢，因为我一直用的这个主题，并没有切换到官方过。所以希望能保持前后的一致性

**Comment by Achuan-2** [comment]
大致调整了下位置，又增加了红色
![image](https://user-images.githubusercontent.com/60436214/129699971-88d71282-06ea-4a60-96f0-d3b174a0f2d7.png)

![image](https://user-images.githubusercontent.com/60436214/129699949-32494b17-483d-47b0-a289-5f67320f0fdc.png)
