### ISSUE TITLE
更新tsundoku主题时遇到的一个奇怪的问题

### ISSUE THREAD

**Issue by UltramarineSky** [Achuan-2/siyuan-themes-tsundoku-dark#11]
![image](https://user-images.githubusercontent.com/54146035/135442951-14481f35-37e5-4d91-b3ff-f217daa4190b.png)

从集市中更新tsundoku主题时出现这个，其他的主题更新正常，遂尝试从Github进行下载更新，但是解压时发现alibaba.svg拒绝访问。
单独下载该文件也说没有权限无法下载，其他的svg文件下载正常，很奇怪。

**Comment by Achuan-2** [comment]
你好，我在主题是可以更新v0.8.6版本的

**Comment by UltramarineSky** [comment]
> 你好，我在主题是可以更新v0.8.6版本的

谢谢回复，我找到原因了，以前往火绒里导入过防护规则，里面有个防止阿里旺旺创建服务和组件的，被殃及池鱼了，之前一直没想到这，很抱歉给你添麻烦了
