### ISSUE TITLE
块嵌入调整margin后在列表中表现不正常

### ISSUE THREAD

**Issue by Duan-Wuya** [Achuan-2/siyuan-themes-tsundoku-dark#12]
块嵌入调整如下margin后（10月1日更新），导致在列表项中表现不正常（左侧无法与列表的bullet对齐）

```css
margin:12px 0px;
```

非正常表现如下：
![image](https://user-images.githubusercontent.com/59379633/135754126-a347315e-0675-4797-8504-358aaede4c58.png)

该语句去掉后如下（与默认主题相符）：
![image](https://user-images.githubusercontent.com/59379633/135754161-9a7c3292-d21a-4f52-9f6b-29c498fcece1.png)

**Comment by Achuan-2** [comment]
谢谢反馈，已修复https://github.com/Achuan-2/siyuan-themes-tsundoku-dark/commit/9b4ac3e601718480c19336fa290402644cf68cc1
