### ISSUE TITLE
1.4.2时列表中的代码块会出现竖线

### ISSUE THREAD

**Issue by regenttsui** [Achuan-2/siyuan-themes-tsundoku-dark#13]
![6A()0}Y}MSILL7SB3L(F5TI](https://user-images.githubusercontent.com/25165069/136879731-5bc34e79-fe8b-47a6-ab03-a05c286aa79f.png)
如图所示，默认主题没有这个问题，估计跟主题左上角的三个点有关系

**Comment by Achuan-2** [comment]
我也刚发现了，这是1.4.2的列表竖线和我代码块冲突了，就把三个点也变成竖线了，晚点看看能不能调整下

**Comment by Achuan-2** [comment]
下次更新修复
