### ISSUE TITLE
代码折叠后，行号并未隐藏

### ISSUE THREAD

**Issue by sevming** [Achuan-2/siyuan-themes-tsundoku-dark#14]

**Comment by Achuan-2** [comment]
谢谢提醒，已修复https://github.com/Achuan-2/siyuan-themes-tsundoku-dark/commit/3e4e1f34b7697d82361801b753841953f3ef26b5#diff-dff3ae40ade5d29630f230c063582d795566bbc4d4d9bace844e205e65325abbR3023-R3027
