### ISSUE TITLE
错误提示文字和背景同色导致看不到

### ISSUE THREAD

**Issue by guidongyuan** [Achuan-2/siyuan-themes-tsundoku-dark#15]
![image](https://user-images.githubusercontent.com/13446866/144158868-7c7c6018-0f21-4cb2-9112-5d33c3a85424.png)

当出现思源错误提示，比如网络异常，错误提示看不到

**Comment by Achuan-2** [comment]
已修复，卸载再重装主题，目前思源集市更新主题没有更新提示
