### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by clifflinmao** [Achuan-2/siyuan-themes-tsundoku-dark#16]
Can you please descripe how to install the theme?? Simply by unzipping and dragging to the 'theme' folder doesn't seems to work.
And if you download from the marketplace, it always failed.

**Comment by Achuan-2** [comment]
I don't know what happened to your computer.
In normal case, you can install form theme market in the SiYuan software.
If you need to manually install it, download the repo as a zip, unzip it and place it in the <workspace>/conf/appearance/themes/ directory of SiYuan Note. And then have to reboot Siyuan Note to choose this theme
