### ISSUE TITLE
更新新版本后，字体变模糊了

### ISSUE THREAD

**Issue by guidongyuan** [Achuan-2/siyuan-themes-tsundoku-dark#17]
Window10 设备

不知道是新版本思源的问题，还是新版本主题的问题，今天发现字体变模糊了
![image](https://user-images.githubusercontent.com/13446866/150454272-ffdb3c72-630e-4074-a8af-00de8efd1f65.png)

上面是themes-tsundoku-dark很早的版本，下面是目前最新的版本

**Comment by Achuan-2** [comment]
应该是主题字体改了吧，现在用的是HarmonyOS_Sans_SC_Regular，你看逗号是不一样的，感觉这个字体比较圆润点吧

**Comment by Achuan-2** [comment]
然后blockquote块也有调整一点透明度

**Comment by Achuan-2** [comment]
下个版本取消blockquote块的透明度
