### ISSUE TITLE
bug：最新版的暗色主题，标签位置偏移

### ISSUE THREAD

**Issue by o-ut-man** [Achuan-2/siyuan-themes-tsundoku-dark#2]
![image](https://user-images.githubusercontent.com/34265164/110508529-0c574980-813c-11eb-86a4-2a4855abd10d.png)

亮色主题正常。 另外建议暗色标签的颜色可以暗一些，感觉在暗色背景下显得太亮眼了些。

**Comment by Achuan-2** [comment]
标签位置偏移具体指的是什么，我两个主题都是设置一样的数值的

**Comment by o-ut-man** [comment]
> 标签位置偏移具体指的是什么，我两个主题都是设置一样的数值的

![image](https://user-images.githubusercontent.com/34265164/110556786-2fa0e980-817a-11eb-8191-f825193d6fcf.png)

就是感觉暗色主题下，标签中的文字没有垂直居中，往下偏移了那么1-2px的样子。不过也有可能只是字体的视觉问题

**Comment by Achuan-2** [comment]
> > 标签位置偏移具体指的是什么，我两个主题都是设置一样的数值的
> 
> ![image](https://user-images.githubusercontent.com/34265164/110556786-2fa0e980-817a-11eb-8191-f825193d6fcf.png)
> 
> 就是感觉暗色主题下，标签中的文字没有垂直居中，往下偏移了那么1-2px的样子。不过也有可能只是字体的视觉问题

好的，v0.2.4已修正
