### ISSUE TITLE
新版本的挖空效果好像有问题

### ISSUE THREAD

**Issue by netdog2019** [Achuan-2/siyuan-themes-tsundoku-dark#20]
新版本的挖空效果好像有问题
1.7.8，win11 64x
设置成挖空的效果后，点击挖空的文本后没有变化，无法显示遮盖的文字。

**Comment by Achuan-2** [comment]
1.7.6 更新后导致关于鼠标点击focus的样式全部失效，主题下个版本把挖空效果改为悬浮翻转，感谢反馈
