### ISSUE TITLE
在列表里面使用引述块时左边的引导线未对齐

### ISSUE THREAD

**Issue by whuwangyong** [Achuan-2/siyuan-themes-tsundoku-dark#21]
![image](https://user-images.githubusercontent.com/5968678/159680980-c9f9108f-619a-45f7-95f1-13773c0c049a.png)

这是官方的主题：
![image](https://user-images.githubusercontent.com/5968678/159681204-adb91336-cb33-402b-8922-3cf7c3d1e673.png)

Win10 + 1.9.2

**Comment by Achuan-2** [comment]
感谢反馈，已修复
11bb965464c3bca7bb23ae4e989a47c9fddf5adc
