### ISSUE TITLE
v2.0.3版本代码块显示异常

### ISSUE THREAD

**Issue by whuwangyong** [Achuan-2/siyuan-themes-tsundoku-dark#24]
![image](https://user-images.githubusercontent.com/5968678/166220306-b1a9b6fd-f6ee-43ca-8e8f-c0c0797e79da.png)

官方主题如下：
![image](https://user-images.githubusercontent.com/5968678/166220290-1caa09dd-78c3-4261-b9ea-8c8b1d950233.png)

**Comment by Achuan-2** [comment]
已修复
