### ISSUE TITLE
【Bug】如果段落中有 ctrl+g 的部分，键盘按“下”键，最多只能到该部分，不能进入下一行

### ISSUE THREAD

**Issue by hesansi** [Achuan-2/siyuan-themes-tsundoku-dark#27]
如下图：
![image](https://user-images.githubusercontent.com/26622554/171321870-e2eb3929-532d-4cbb-b285-ccce6a5403c7.png)
![image](https://user-images.githubusercontent.com/26622554/171321924-4bd2dd91-baca-4f63-87fb-01bb47c4ea0c.png)
![image](https://user-images.githubusercontent.com/26622554/171321948-11f105da-d0bb-449f-a703-b96e51fef4ea.png)
键盘按“下”键，最多只能到“delegate*”之前，会被卡住，无法进入下一行。
不仅是普通段落，无序列表中也有相同的问题。
默认主题和 Tsundoku Light 主题没有该问题（ Tsundoku Light 是老版本，未更新）。

**Comment by Achuan-2** [comment]
你好，我这里没复现出来

**Comment by hesansi** [comment]
> 你好，我这里没复现出来
麻烦使用下面这段试试看：

* ### 02 References and dependencies

  * 依赖：当一个类型（class 或 struct）使用了另一个类型，前者就依赖了后者

    * 编译时：Unity 在编译一个脚本时，需要先获取该脚本中依赖的类型和代码
    * 运行时：编译好的代码在运行时，需要先获取它依赖的类型和代码
  * 程序集依赖：如果有依赖关系的两个类型，分别在两个程序集中，那么就需要添加程序集之间的引用

    * 控制程序集之间的引用关系：使用 `Assembly Definition` 的配饰参数（后面有解析 #TODO#）

      * `Auto Referenced`（默认勾选）：预定义程序集是否自动引用该程序集（默认勾选）
      * `Assembly Definition Reference`：引用由 Assembly Definition 定义的程序集
      * `Override Reference`（默认不勾选） + `Assembly Reference`：是否引用预先编译的程序集（比如 plugin）

        * 勾选 `Override Reference` 后，出现 `Assembly Reference` 配置项
      * `No Engine References`（默认不勾选）：是否引用 UnityEditor 或 UnityEngine 程序集

**Comment by Achuan-2** [comment]
已修复https://github.com/Achuan-2/siyuan-themes-tsundoku-dark/commit/91cdeaf253f11e94eafb63afb345b3c4f051dc1a
