### ISSUE TITLE
👍最爱的思源主题,提两个小功能

### ISSUE THREAD

**Issue by Mokadao** [Achuan-2/siyuan-themes-tsundoku-dark#3]
- 希望能在打开多窗口时,聚焦的窗口可以表现更明显些
比如加个更亮的外边框或者其他窗口变暗一些.
- 希望文档左侧的空白(功能)区可以缩小一些

**Comment by Achuan-2** [comment]
主题更新了吗，多窗口聚焦目前我觉得已经很明显了，加外边框暂时做不到
文档左侧的留白我觉得刚好呀，不知道是不是不同屏幕显示的差别

**Comment by Achuan-2** [comment]
好吧，多窗口聚焦可以做外边框的闪现的，我等会研究下

**Comment by Achuan-2** [comment]
不好搞，因为加了边框或者高亮，也会作用于单窗口效果，这样会很难看。等官方改进类名吧

**Comment by Achuan-2** [comment]
你说的“希望文档左侧的空白(功能)区可以缩小一些”是指的多窗口时吗，确实有点大，但是正如前面所说，我自己没法改，改了之后单窗口的左侧也缩小了，可以向官方提建议哈
![image](https://user-images.githubusercontent.com/60436214/111298308-90a05400-8689-11eb-8ff0-462f5f61d08d.png)

**Comment by Mokadao** [comment]
收到 谢谢  我说的边框或者非聚焦窗口变暗大概这个意思
![image](https://user-images.githubusercontent.com/37317230/111401608-912a0080-8704-11eb-9109-c5e26e212dae.png)

**Comment by Achuan-2** [comment]
> 收到 谢谢 我说的边框或者非聚焦窗口变暗大概这个意思
> ![image](https://user-images.githubusercontent.com/37317230/111401608-912a0080-8704-11eb-9109-c5e26e212dae.png)

我知道这个意思，但是我做不到多窗口的效果不影响单窗口。而且我觉得多窗口的话，就我自己而言，没必要太区分开当前窗口和其他窗口，目前的效果对我来说已经够用，有种多此一举的感觉。目前应该不会再尝试

**Comment by Achuan-2** [comment]
> 收到 谢谢 我说的边框或者非聚焦窗口变暗大概这个意思
> ![image](https://user-images.githubusercontent.com/37317230/111401608-912a0080-8704-11eb-9109-c5e26e212dae.png)

你好。我想了一下，如果无法从激活窗口的角度进行修改，那就可以从非激活窗口角度出发，实现您说的窗口变暗效果
效果大概是这样，试用一会后可以再优化
![思源多窗口](https://user-images.githubusercontent.com/60436214/111568409-a9208380-87db-11eb-8316-c7d26dd39afa.gif)
![思源多窗口light](https://user-images.githubusercontent.com/60436214/111569264-40d2a180-87dd-11eb-8f45-efa13538f779.gif)
