### ISSUE TITLE
【外观】无序列表中的三级标题左边的竖线，以前是居中的，现在靠上显示了

### ISSUE THREAD

**Issue by hesansi** [Achuan-2/siyuan-themes-tsundoku-dark#30]
如图：
![image](https://user-images.githubusercontent.com/26622554/173233548-5dd5a128-20b5-4aff-b50f-187da302b0b7.png)

**Comment by hesansi** [comment]
![image](https://user-images.githubusercontent.com/26622554/173488300-af9366e6-da19-4b4b-a2ae-49b3abaf3a7c.png)
试了下，改这行就好了，大佬麻烦更新下
另外赞美大佬，思源和这个主题在我这边已经强绑定了

**Comment by Achuan-2** [comment]
谢谢您的喜欢，只是分享简单的css主题，称不上大佬hhh
已修复https://github.com/Achuan-2/siyuan-themes-tsundoku-dark/commit/f9144a227b6a11cb270f323ebb551b880d8a2066#diff-dff3ae40ade5d29630f230c063582d795566bbc4d4d9bace844e205e65325abb
