### ISSUE TITLE
【外观】代码块的行索引靠右了几像素，与代码块有点重叠

### ISSUE THREAD

**Issue by hesansi** [Achuan-2/siyuan-themes-tsundoku-dark#31]
默认主题：
![image](https://user-images.githubusercontent.com/26622554/174051362-f6c5644f-d26a-4b88-b0a6-071de04a5d63.png)
本主题：
![image](https://user-images.githubusercontent.com/26622554/174051597-ec71bd0a-d520-4ba0-a918-ad3dcd276ee9.png)

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/174214495-3ff4e0e4-1a69-43e9-a521-4df165911894.png)
我这里没问题
