### ISSUE TITLE
请问可以让h4和h5的样式区分更明显吗

### ISSUE THREAD

**Issue by patialo** [Achuan-2/siyuan-themes-tsundoku-dark#32]
我看作者的代码里h3用的是伪元素，前面设计了一个竖线。
那么h4 可不可以来一个横线呢，或者改变一下颜色？确实h4和h5不太好区分，不够直观

**Comment by Achuan-2** [comment]
因为我比较少用h4，之后会想想。有需要的话你可以自己先改改

**Comment by patialo** [comment]
> 因为我比较少用h4，之后会想想。有需要的话你可以自己先改改

OK，感谢回复
