### ISSUE TITLE
可以让h1靠左吗？

### ISSUE THREAD

**Issue by liuzhenggang** [Achuan-2/siyuan-themes-tsundoku-dark#33]
h1居中不太习惯，请问大佬，我怎么能自己设置为靠左呢？

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/180588689-9fbbe028-52a8-44cd-a1e7-bbcc409926bc.png)
打开主题文件夹，搜索theme.css，把h1的text-align这行删掉

**Comment by liuzhenggang** [comment]
好的，多谢
