### ISSUE TITLE
行内代码样式希望改一下

### ISSUE THREAD

**Issue by patialo** [Achuan-2/siyuan-themes-tsundoku-dark#36]
![image](https://user-images.githubusercontent.com/31113826/192823510-62bf774e-d2bd-4410-b892-6171d090e190.png)
新版本行内代码不明显了

**Comment by Achuan-2** [comment]
更新了最新主题了吗

**Comment by patialo** [comment]
不好意思，是我没更新，light提示我更新了，但是dark没有更新按钮，所以我以为dark没更
