### ISSUE TITLE
请问主题文件中哪个css文件可以做到更新后不用重新自定义

### ISSUE THREAD

**Issue by patialo** [Achuan-2/siyuan-themes-tsundoku-dark#37]
因为我有一些自定义样式的需求，每一次更新主题后都得手动重新添加，但是我找不到一劳永逸的办法去存放它们，望指点，谢谢

**Comment by Achuan-2** [comment]
主题文件夹新建custom.css
如果是所有主题都想要一样的样式，可以用代码片段
![Snipaste_2022-10-29_11-01-52](https://user-images.githubusercontent.com/60436214/198793413-60c7bcc8-dee3-48d2-a83f-0281c3b434c9.png)

**Comment by patialo** [comment]
![image](https://user-images.githubusercontent.com/31113826/198795040-c4d1ee72-e24c-4cd4-9868-9bdd8ff99387.png)
使用代码片段时报错

**Comment by Achuan-2** [comment]
在data文件夹新建一个snippets文件夹就可以了

**Comment by patialo** [comment]
ok，感谢！

另外，问个问题，我用的是docker版本，更改css文件的内容后，浏览器无法即时刷新就更改成功，是什么原因（甚至重启思源也不一定能成功），有什么解决之道吗

**Comment by Achuan-2** [comment]
不太懂，可能是思源有缓存吧，在网络选项卡里去掉缓存，ctrl+shift+i打开开发者模式刷新？

**Comment by patialo** [comment]
> 不太懂，可能是思源有缓存吧，在网络选项卡里去掉缓存，ctrl+shift+i打开开发者模式刷新？

清除缓存刷新就可以了，感谢大佬！
