### ISSUE TITLE
思源笔记更新1.1.6之后代码块语言显示错位

### ISSUE THREAD

**Issue by risoyo** [Achuan-2/siyuan-themes-tsundoku-dark#4]
部署方式：docker
思源笔记版本：1.1.6
主题版本：v0.3.4，3月30日上午更新思源笔记版本后在思源笔记集市中手动更新
现象：
在1.1.5时，每个代码块会显示所属语言，但是更新到1.1.6之后，代码块语言显示错位到了文档右上方，并且整个文档中所有代码块的语言都消失了，只在文档右上方显示第一个代码块的语言

**Comment by risoyo** [comment]
更新前：
![image](https://user-images.githubusercontent.com/11912562/112870416-c5cc8d80-90f0-11eb-9570-353d0d7eb0e4.png)


更新后：
![image](https://user-images.githubusercontent.com/11912562/112870523-e268c580-90f0-11eb-806d-dc78e22baf70.png)
![image](https://user-images.githubusercontent.com/11912562/112870551-eac10080-90f0-11eb-9460-37d801a31bdc.png)

**Comment by risoyo** [comment]
恩。。试了下mixure-light是没有问题的
![image](https://user-images.githubusercontent.com/11912562/112871331-bef24a80-90f1-11eb-8dd6-522f2163986d.png)
![image](https://user-images.githubusercontent.com/11912562/112871366-c7e31c00-90f1-11eb-8860-97fbaa3ac848.png)
没有mixure-dark中的右上角层叠代码语言的问题，主题版本和dark是一致的，都是今天更新的最新版

**Comment by Achuan-2** [comment]
你好，尝试重启思源或者重新安装主题，mixture 的主题代码样式和我本地的不一样，连阴影都消失了

**Comment by risoyo** [comment]
> 你好，尝试重启思源或者重新安装主题，mixture 的主题代码样式和我本地的不一样，连阴影都消失了

好了，感谢作者大大，重启都不行，把docker容器干掉之后，再把宿主机的conf目录删掉，完全初始化之后重新安装主题才正常了
