### ISSUE TITLE
日历功能在我这里出现无法识别问题

### ISSUE THREAD

**Issue by Hai-de** [Achuan-2/siyuan-themes-tsundoku-dark#41]
这可能是我的日历模版有些复杂
![屏幕截图_20230202_112110](https://user-images.githubusercontent.com/69635508/216224030-b48d412a-17a0-4a86-94fb-b4b292b355e5.png)
上面是这个主题的日历功能，下面则是思源的日历功能
![屏幕截图_20230202_112126](https://user-images.githubusercontent.com/69635508/216224182-35dbaf7f-8bdd-43a0-8dd0-461478804266.png)
以下就是我的日历模版
`/daily note/{{now | date "2006/01"}}/{{now |date "2006-01-02"}}{{last (slice (list " 日曜日" " 月曜日" " 火曜日" " 水曜日" " 木曜日" " 金曜日" " 土曜日" ) 0 (add (mod (div (now.Sub (toDate "2006-01-02" "2021-05-02")).Hours 24) 7 ) 1))}}`

**Comment by Achuan-2** [comment]
日历功能是fork的，https://github.com/HowcanoeWang/calendar/tree/230201
源代码里确实对于模板实际是没有解析的，只是提取 `/daily note/{{now | date "2006/01"}}/{{now |date "`后面的内容，所以导致无法识别。建议向原作者反馈

**Comment by Hai-de** [comment]
@Achuan-2 那多谢了
