### ISSUE TITLE
标题块的命名和别名位置偏移

### ISSUE THREAD

**Issue by o-ut-man** [Achuan-2/siyuan-themes-tsundoku-dark#5]
![image](https://user-images.githubusercontent.com/34265164/113083197-55b42980-920e-11eb-9db5-f3eb8faba299.png)
段落块正常
---
现在标题块距离上面一个内容块的间距是不是调小了

**Comment by Achuan-2** [comment]
感谢反馈
V姐调的，不关我事
下一个版本修复
