### ISSUE TITLE
无法切换到明亮模式下的主题

### ISSUE THREAD

**Issue by Crowds21** [Achuan-2/siyuan-themes-tsundoku-dark#8]
![image](https://user-images.githubusercontent.com/48215334/120654338-2fcc2f00-c4b4-11eb-88ad-a6b6abddee03.png)

下载后,明亮模式中,并没有该主题

**Comment by Achuan-2** [comment]
关闭重启试试

**Comment by Crowds21** [comment]
> 关闭重启试试

抱歉,看主题封面我还以为是只要下一次,然后按快捷键能够直接切换呢,哈哈哈哈
