### ISSUE TITLE
行内数学公式字号大小出现明显错误

### ISSUE THREAD

**Issue by AsciimovLee** [Achuan-2/siyuan-themes-tsundoku-dark#9]
块级公式正确渲染
![image](https://user-images.githubusercontent.com/73106094/123073681-3877ab80-d449-11eb-90e7-38cbc4501dc9.png)
使用 `\displaystyle` 模式后的行内公式
![image](https://user-images.githubusercontent.com/73106094/123073542-141bcf00-d449-11eb-84de-27f330d9df64.png)
未使用 `\displaystyle` 模式后的行内公式
![image](https://user-images.githubusercontent.com/73106094/123073585-1d0ca080-d449-11eb-8186-7c5cc5bc1ccb.png)
昼夜主题均存在类似问题

**Comment by Achuan-2** [comment]
默认主题没有这个问题吗

**Comment by AsciimovLee** [comment]
是的

**Comment by Achuan-2** [comment]
之前是想把调整下分式大小，看来会有蛮多问题的，干脆全删了
